// <auto-generated />
using System;
using HomeLedger.Infrastructure.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace HomeLedger.Infrastructure.Data.Migrations
{
    [DbContext(typeof(HomeLedgerDbContext))]
    [Migration("20260620194300_AccountKindAndImportLlmTracking")]
    partial class AccountKindAndImportLlmTracking
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "10.0.0");

            modelBuilder.Entity("HomeLedger.Core.Entities.Account", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("AccountNumberLast4")
                        .HasColumnType("TEXT");

                    b.Property<int?>("ImportProfileId")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Institution")
                        .HasColumnType("TEXT");

                    b.Property<bool>("IsActive")
                        .HasColumnType("INTEGER");

                    b.Property<int>("Kind")
                        .HasColumnType("INTEGER");

                    b.Property<int>("LedgerEntityId")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("ImportProfileId");

                    b.HasIndex("LedgerEntityId");

                    b.ToTable("Accounts");
                });

            modelBuilder.Entity("HomeLedger.Core.Entities.BudgetLimit", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int>("CategoryId")
                        .HasColumnType("INTEGER");

                    b.Property<DateOnly?>("CustomEndDate")
                        .HasColumnType("TEXT");

                    b.Property<DateOnly?>("CustomStartDate")
                        .HasColumnType("TEXT");

                    b.Property<bool>("IsActive")
                        .HasColumnType("INTEGER");

                    b.Property<int?>("LedgerEntityId")
                        .HasColumnType("INTEGER");

                    b.Property<decimal>("LimitAmount")
                        .HasColumnType("TEXT");

                    b.Property<int>("Period")
                        .HasColumnType("INTEGER");

                    b.Property<decimal>("WarningThresholdPercent")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("CategoryId");

                    b.HasIndex("LedgerEntityId");

                    b.ToTable("BudgetLimits");
                });

            modelBuilder.Entity("HomeLedger.Core.Entities.Category", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int>("CategoryGroupId")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("IsActive")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("IsIncome")
                        .HasColumnType("INTEGER");

                    b.Property<int?>("LedgerEntityId")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int>("SortOrder")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("CategoryGroupId");

                    b.HasIndex("LedgerEntityId");

                    b.HasIndex("Name", "LedgerEntityId")
                        .IsUnique();

                    b.ToTable("Categories");
                });

            modelBuilder.Entity("HomeLedger.Core.Entities.CategoryGroup", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<bool>("IsActive")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("IsIncome")
                        .HasColumnType("INTEGER");

                    b.Property<int?>("LedgerEntityId")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int>("SortOrder")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("LedgerEntityId");

                    b.HasIndex("Name", "LedgerEntityId")
                        .IsUnique();

                    b.ToTable("CategoryGroups");
                });

            modelBuilder.Entity("HomeLedger.Core.Entities.ImportBatch", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("TEXT");

                    b.Property<int?>("AccountId")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("AutoAccept")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime?>("CompletedAt")
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("TEXT");

                    b.Property<string>("FileName")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("FileSha256")
                        .HasColumnType("TEXT");

                    b.Property<long?>("FileSizeBytes")
                        .HasColumnType("INTEGER");

                    b.Property<int?>("LedgerEntityId")
                        .HasColumnType("INTEGER");

                    b.Property<string>("LlmAvailabilityNotes")
                        .HasColumnType("TEXT");

                    b.Property<bool>("LlmCategorizationAvailable")
                        .HasColumnType("INTEGER");

                    b.Property<int>("LlmCategorizedCount")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("LlmClassificationAvailable")
                        .HasColumnType("INTEGER");

                    b.Property<int>("LlmClassifiedCount")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("LlmConfiguredAtImport")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("PdfExtractedWithLlm")
                        .HasColumnType("INTEGER");

                    b.Property<int>("Status")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("AccountId");

                    b.HasIndex("LedgerEntityId");

                    b.HasIndex("FileSha256", "FileSizeBytes", "AccountId");

                    b.ToTable("ImportBatches");
                });

            modelBuilder.Entity("HomeLedger.Core.Entities.ImportItem", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<decimal>("Amount")
                        .HasColumnType("TEXT");

                    b.Property<DateOnly>("Date")
                        .HasColumnType("TEXT");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("ExternalId")
                        .HasColumnType("TEXT");

                    b.Property<string>("ImportBatchId")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int?>("ResultingTransactionId")
                        .HasColumnType("INTEGER");

                    b.Property<string>("SkipReason")
                        .HasColumnType("TEXT");

                    b.Property<int>("Status")
                        .HasColumnType("INTEGER");

                    b.Property<int?>("SuggestedCategoryId")
                        .HasColumnType("INTEGER");

                    b.Property<string>("SuggestedNotes")
                        .HasColumnType("TEXT");

                    b.Property<string>("SuggestedSkipReason")
                        .HasColumnType("TEXT");

                    b.Property<string>("SuggestionSource")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("ImportBatchId");

                    b.HasIndex("SuggestedCategoryId");

                    b.ToTable("ImportItems");
                });

            modelBuilder.Entity("HomeLedger.Core.Entities.ImportProfile", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("TEXT");

                    b.Property<bool>("IsActive")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("IsDefault")
                        .HasColumnType("INTEGER");

                    b.Property<int>("LedgerEntityId")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<bool>("UseLlmForUnmatched")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("LedgerEntityId");

                    b.HasIndex("Name", "LedgerEntityId")
                        .IsUnique();

                    b.ToTable("ImportProfiles");
                });

            modelBuilder.Entity("HomeLedger.Core.Entities.ImportSkipRule", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int>("ImportProfileId")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("IsActive")
                        .HasColumnType("INTEGER");

                    b.Property<int>("MatchType")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Pattern")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("SkipKind")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int>("SortOrder")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("ImportProfileId");

                    b.ToTable("ImportSkipRules");
                });

            modelBuilder.Entity("HomeLedger.Core.Entities.LedgerEntity", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Color")
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("TEXT");

                    b.Property<bool>("IsActive")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("Name")
                        .IsUnique();

                    b.ToTable("Entities");
                });

            modelBuilder.Entity("HomeLedger.Core.Entities.Transaction", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int?>("AccountId")
                        .HasColumnType("INTEGER");

                    b.Property<decimal>("Amount")
                        .HasColumnType("TEXT");

                    b.Property<int>("CategoryId")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("TEXT");

                    b.Property<DateOnly>("Date")
                        .HasColumnType("TEXT");

                    b.Property<string>("ExternalId")
                        .HasColumnType("TEXT");

                    b.Property<string>("ImportBatchId")
                        .HasColumnType("TEXT");

                    b.Property<int>("LedgerEntityId")
                        .HasColumnType("INTEGER");

                    b.Property<int?>("LinkedTransactionId")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Notes")
                        .HasColumnType("TEXT");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("AccountId");

                    b.HasIndex("CategoryId");

                    b.HasIndex("Date");

                    b.HasIndex("LedgerEntityId");

                    b.HasIndex("LinkedTransactionId");

                    b.HasIndex("ExternalId", "AccountId")
                        .IsUnique()
                        .HasFilter("[ExternalId] IS NOT NULL");

                    b.ToTable("Transactions");
                });

            modelBuilder.Entity("HomeLedger.Core.Entities.Account", b =>
                {
                    b.HasOne("HomeLedger.Core.Entities.ImportProfile", "ImportProfile")
                        .WithMany("Accounts")
                        .HasForeignKey("ImportProfileId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.HasOne("HomeLedger.Core.Entities.LedgerEntity", "LedgerEntity")
                        .WithMany("Accounts")
                        .HasForeignKey("LedgerEntityId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("ImportProfile");

                    b.Navigation("LedgerEntity");
                });

            modelBuilder.Entity("HomeLedger.Core.Entities.BudgetLimit", b =>
                {
                    b.HasOne("HomeLedger.Core.Entities.Category", "Category")
                        .WithMany("BudgetLimits")
                        .HasForeignKey("CategoryId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("HomeLedger.Core.Entities.LedgerEntity", "LedgerEntity")
                        .WithMany()
                        .HasForeignKey("LedgerEntityId");

                    b.Navigation("Category");

                    b.Navigation("LedgerEntity");
                });

            modelBuilder.Entity("HomeLedger.Core.Entities.Category", b =>
                {
                    b.HasOne("HomeLedger.Core.Entities.CategoryGroup", "CategoryGroup")
                        .WithMany("Categories")
                        .HasForeignKey("CategoryGroupId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("HomeLedger.Core.Entities.LedgerEntity", "LedgerEntity")
                        .WithMany()
                        .HasForeignKey("LedgerEntityId");

                    b.Navigation("CategoryGroup");

                    b.Navigation("LedgerEntity");
                });

            modelBuilder.Entity("HomeLedger.Core.Entities.CategoryGroup", b =>
                {
                    b.HasOne("HomeLedger.Core.Entities.LedgerEntity", "LedgerEntity")
                        .WithMany()
                        .HasForeignKey("LedgerEntityId");

                    b.Navigation("LedgerEntity");
                });

            modelBuilder.Entity("HomeLedger.Core.Entities.ImportBatch", b =>
                {
                    b.HasOne("HomeLedger.Core.Entities.Account", "Account")
                        .WithMany()
                        .HasForeignKey("AccountId");

                    b.HasOne("HomeLedger.Core.Entities.LedgerEntity", "LedgerEntity")
                        .WithMany()
                        .HasForeignKey("LedgerEntityId");

                    b.Navigation("Account");

                    b.Navigation("LedgerEntity");
                });

            modelBuilder.Entity("HomeLedger.Core.Entities.ImportItem", b =>
                {
                    b.HasOne("HomeLedger.Core.Entities.ImportBatch", "ImportBatch")
                        .WithMany("Items")
                        .HasForeignKey("ImportBatchId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("HomeLedger.Core.Entities.Category", "SuggestedCategory")
                        .WithMany()
                        .HasForeignKey("SuggestedCategoryId");

                    b.Navigation("ImportBatch");

                    b.Navigation("SuggestedCategory");
                });

            modelBuilder.Entity("HomeLedger.Core.Entities.ImportProfile", b =>
                {
                    b.HasOne("HomeLedger.Core.Entities.LedgerEntity", "LedgerEntity")
                        .WithMany()
                        .HasForeignKey("LedgerEntityId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("LedgerEntity");
                });

            modelBuilder.Entity("HomeLedger.Core.Entities.ImportSkipRule", b =>
                {
                    b.HasOne("HomeLedger.Core.Entities.ImportProfile", "ImportProfile")
                        .WithMany("Rules")
                        .HasForeignKey("ImportProfileId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("ImportProfile");
                });

            modelBuilder.Entity("HomeLedger.Core.Entities.Transaction", b =>
                {
                    b.HasOne("HomeLedger.Core.Entities.Account", "Account")
                        .WithMany("Transactions")
                        .HasForeignKey("AccountId");

                    b.HasOne("HomeLedger.Core.Entities.Category", "Category")
                        .WithMany("Transactions")
                        .HasForeignKey("CategoryId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("HomeLedger.Core.Entities.LedgerEntity", "LedgerEntity")
                        .WithMany("Transactions")
                        .HasForeignKey("LedgerEntityId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("HomeLedger.Core.Entities.Transaction", null)
                        .WithMany()
                        .HasForeignKey("LinkedTransactionId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.Navigation("Account");

                    b.Navigation("Category");

                    b.Navigation("LedgerEntity");
                });

            modelBuilder.Entity("HomeLedger.Core.Entities.Account", b =>
                {
                    b.Navigation("Transactions");
                });

            modelBuilder.Entity("HomeLedger.Core.Entities.Category", b =>
                {
                    b.Navigation("BudgetLimits");

                    b.Navigation("Transactions");
                });

            modelBuilder.Entity("HomeLedger.Core.Entities.CategoryGroup", b =>
                {
                    b.Navigation("Categories");
                });

            modelBuilder.Entity("HomeLedger.Core.Entities.ImportBatch", b =>
                {
                    b.Navigation("Items");
                });

            modelBuilder.Entity("HomeLedger.Core.Entities.ImportProfile", b =>
                {
                    b.Navigation("Accounts");

                    b.Navigation("Rules");
                });

            modelBuilder.Entity("HomeLedger.Core.Entities.LedgerEntity", b =>
                {
                    b.Navigation("Accounts");

                    b.Navigation("Transactions");
                });
#pragma warning restore 612, 618
        }
    }
}
